isaweb:
   image: tp33/django:1.2
   external_links:
     - mysql:db
   volumes:
     - .:/app
   command: mod_wsgi-express start-server --working-directory /app --url-alias /static /app/marketplace/static /app/marketplace/wsgi.py &
   ports:
    - "8000:8000"