models:
   build: .
   external_links:
     - mysql:db
   volumes:
     - ./models/:/app
   command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures/db1.json && mod_wsgi-express start-server --reload-on-changes /app/marketplace/wsgi.py"

   ports:
     - "8001:8000"

exp:
   build: .
   links:
     - models:models-api
     - kafka:kafka
     - es:es
   volumes:
     - ./exp/:/app
   command: mod_wsgi-express start-server --reload-on-changes /app/experience_API/wsgi.py &
   ports:
     - "8002:8000"

web:
   build: .
   links:
     - exp:exp-api
   volumes:
     - ./web/:/app
   command: mod_wsgi-express start-server --reload-on-changes /app/web_interface/wsgi.py &
   ports:
     - "8000:8000"

web2:
   build: .
   links:
    - exp:exp-api
   volumes:
    - ./web/:/app
   command: mod_wsgi-express start-server --reload-on-changes /app/web_interace/wsgi.py &
   ports:
    - "8004:8000"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   build: .
   environment:
     - PYTHONUNBUFFERED=0
   links:
     - kafka:kafka
     - es:es
   volumes:
     - ./batch/:/batch-script
   command: python /batch-script/kafka_ES_worker.py &
   ports:
     - "8003:8000"
   
loadbalancer:
   image: galexrt/pen:latest
   environment:
    - w stats.html
    - l loadbalancer.log
   links:
    - web:web-api
    - web2:web2-api
   container_name: loadbalancer
   command: pen -u root -p 8005:8000
   ports:
    - "8005:8000"

spark-master:
   image: gettyimages/spark
   command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
   container_name: spark-master
   environment:
     MASTER: spark://spark-master:7077
     SPARK_CONF_DIR: /conf
   expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
   ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
   volumes:
    - ./data:/tmp/data

spark-worker:
   image: gettyimages/spark
   command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
   container_name: spark-worker
   hostname: spark-worker
   environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
   links:
    - spark-master
   expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
   ports:
    - 8081:8081
   volumes:
    - ./data:/tmp/data

